name: Dynamo Util Build

on:
  push:
    branches:
      - main
jobs:
  setup-build-workflow:
    runs-on: ubuntu-latest

    outputs:
      IS_PRERELEASE: ${{ steps.set-vars.outputs.IS_PRERELEASE }}
      IS_MERGE_TO_MAIN: ${{ steps.set-vars.outputs.IS_MERGE_TO_MAIN }}
      IS_MERGE_TO_DEVELOP: ${{ steps.set-vars.outputs.IS_MERGE_TO_DEVELOP }}
      REF_TO_BUILD_AND_TAG: ${{ steps.set-vars.outputs.REF_TO_BUILD_AND_TAG }}
      IS_DEPENDABOT_PR: ${{ steps.actor_check.outputs.IS_DEPENDABOT_PR }}

    steps:
      - name: Set default env variables
        id: set-vars
        uses: actions/github-script@v6
        with:
          script: |
            const targetRef = '${{ github.base_ref }}';
            const sourceRef = '${{ github.head_ref }}';
            const mergeRef = '${{ github.ref }}';

            const prIsDraft = '${{ github.event.pull_request.draft }}' === 'true';
            const prMergedToMain = mergeRef === 'refs/heads/main';

            const isPreRelease = !prMergedToMain

            // For a detailed explanation of why we use different refs for different scenarios
            // see https://docs.github.com/en/rest/reference/pulls#get-a-pull-request
            const refToBuildAndTag = isPreRelease ? sourceRef : mergeRef;

            Object.entries({
              IS_PRERELEASE: isPreRelease,
              IS_MERGE_TO_MAIN: prMergedToMain,
              REF_TO_BUILD_AND_TAG: refToBuildAndTag,
            }).forEach(pair => {
              core.setOutput(...pair);
              console.info(...pair);
            });

      - name: Check if Dependabot PR
        id: actor_check
        uses: actions/github-script@v6
        with:
          script: |
            const actor = '${{ github.actor}}';
            const knownDependabotNames = [
              'dependabot[bot]',
              'dependabot'
            ];
            const isDependabotPR = knownDependabotNames.includes(actor);
            core.info(`Is Dependabot PR: ${isDependabotPR}`);
            core.setOutput('IS_DEPENDABOT_PR', isDependabotPR);

  get-version:
    runs-on: ubuntu-latest
    needs: [setup-build-workflow]

    outputs:
      NEXT_VERSION: ${{ steps.get-version.outputs.NEXT_VERSION }}
      NEXT_VERSION_NO_PREFIX: ${{ steps.get-version.outputs.NEXT_VERSION_NO_PREFIX }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Includes all history for all branches and tags

      - id: get-version
        uses: joemcbride/git-version-lite@v3.0.0
        with:
          calculate-prerelease-version: ${{ needs.setup-build-workflow.outputs.IS_PRERELEASE }}
          branch-name: ${{ needs.setup-build-workflow.outputs.REF_TO_BUILD_AND_TAG }}
          tag-prefix: dynamo-util-
          fallback-to-no-prefix-search: false
          default-release-type: minor
          create-ref: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "The next version is ${{ env.NEXT_VERSION }}"
          echo "The next version without the prefix is ${{ env.NEXT_VERSION_NO_PREFIX }}"

  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: [get-version, setup-build-workflow]
    permissions:
        contents: read
        packages: write
        checks: write
    env:
      NEXT_VERSION: ${{ needs.get-version.outputs.NEXT_VERSION }}
      NEXT_VERSION_NO_PREFIX: ${{ needs.get-version.outputs.NEXT_VERSION_NO_PREFIX }}

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Restore
        run: |
          dotnet restore

      - name: Set Version
        run: |
            sed -i.bak 's/<version>.*<\/version>/<version>${{ env.NEXT_VERSION_NO_PREFIX }}<\/version>/g' "./dynamo-util.nuspec"

      - name: Build
        run: |
          dotnet build --no-restore -c Release
      
      - name: Pack
        run: |
          dotnet pack -o build

      - name: Publish
        run: |
          dotnet nuget push "./build/dynamo-util.${{ env.NEXT_VERSION_NO_PREFIX }}.nupkg" -k ${{ secrets.NUGET_API_KEY }}

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          rm *.bak


      - name: Status
        if: always()
        continue-on-error: true
        run: echo "🍏 This job's status is ${{ job.status }}."
